WITH DATA1 AS (
    SELECT
        *
    FROM
        USER_INFO
    WHERE
        JOINED LIKE '2021%'
), DATA2 AS (
    SELECT
        DATA1.*, OS.SALES_DATE
    FROM
        DATA1 INNER JOIN ONLINE_SALE OS
    ON
        DATA1.USER_ID = OS.USER_ID
    GROUP BY
        YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), DATA1.USER_ID
)

SELECT
    YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(*) PUCHASED_USERS, ROUND(
        COUNT(*) / (
            SELECT COUNT(*)
            FROM DATA1
            GROUP BY YEAR(JOINED)
        )
    , 1) PUCHAED_RATIO
FROM
    DATA2
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY
    YEAR ASC, MONTH ASC;
