WITH SUWON AS (
    SELECT PM_VAL1, PM_VAL2, YEAR(YM) YEAR
    FROM AIR_POLLUTION
    WHERE LOCATION2 LIKE '수원'
)

SELECT YEAR, ROUND(AVG(PM_VAL1), 2) PM10, ROUND(AVG(PM_VAL2), 2) 'PM2.5'
FROM SUWON
GROUP BY YEAR
ORDER BY YEAR ASC
