WITH YEAR_GRADE AS (
    SELECT EMP_NO, SUM(SCORE) YEAR_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
), TOP_EMP AS (
    SELECT EMP_NO, YEAR_SCORE
    FROM YEAR_GRADE
    WHERE YEAR_SCORE = (SELECT MAX(YEAR_SCORE) FROM YEAR_GRADE)
)

SELECT T.YEAR_SCORE SCORE, H.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM TOP_EMP T INNER JOIN HR_EMPLOYEES H
ON T.EMP_NO = H.EMP_NO
