SELECT EXTRACT(MONTH FROM START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-mm-dd')
        AND START_DATE <= TO_DATE('2022-10-31', 'YYYY-mm-DD')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AND (START_DATE >= TO_DATE('2022-08-01', 'YYYY-mm-dd') AND START_DATE <= TO_DATE('2022-10-31', 'YYYY-mm-DD'))
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
-- HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC
