WITH MAX_LEN AS (
    SELECT FISH_TYPE, MAX(LENGTH) LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT A.ID, B.FISH_NAME, C.LENGTH
FROM FISH_INFO A INNER JOIN FISH_NAME_INFO B INNER JOIN MAX_LEN C
ON A.FISH_TYPE = B.FISH_TYPE AND A.FISH_TYPE = C.FISH_TYPE
WHERE A.LENGTH = C.LENGTH
ORDER BY A.ID
