SELECT *
FROM(
    SELECT B.ANIMAL_ID, B.NAME
    FROM ANIMAL_INS A RIGHT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID=B.ANIMAL_ID
    WHERE A.DATETIME IS NOT NULL
    ORDER BY B.DATETIME-A.DATETIME DESC
)
WHERE ROWNUM<3
