SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS LIKE 'DONE'
GROUP BY U.USER_ID
HAVING U.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS LIKE 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
ORDER BY TOTAL_SALES ASC;
