SELECT ORDER_ID, PRODUCT_ID, TO_CHAR(OUT_DATE, 'YYYY-mm-dd') OUT_DATE, (
    CASE
    WHEN OUT_DATE IS NULL THEN '출고미정'
    WHEN OUT_DATE <= TO_DATE('2022-05-01', 'YYYY-mm-dd') THEN '출고완료'
    ELSE '출고대기'
    END
) 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID ASC;
