WITH FISH_10 AS (
    SELECT *, (
        CASE
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END
    ) LENGTH_10
    FROM FISH_INFO
), FISH_AVG AS (
    SELECT FISH_TYPE, AVG(LENGTH_10) AVG_LEN
    FROM FISH_10
    GROUP BY FISH_TYPE
)

SELECT COUNT(A.ID) FISH_COUNT, MAX(A.LENGTH) MAX_LENGTH, A.FISH_TYPE
FROM FISH_INFO A INNER JOIN FISH_AVG B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.AVG_LEN >= 33
GROUP BY A.FISH_TYPE
ORDER BY A.FISH_TYPE
