WITH FE AS (
    SELECT SUM(CODE) SUM_CODE
    FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY LIKE 'Front End'
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, FE F
WHERE D.SKILL_CODE & F.SUM_CODE
ORDER BY D.ID
