WITH DATA1 AS (
    SELECT
        *, COUNT(*) REVIEW_CNT
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID   
), DATA2 AS (
    SELECT
        MEMBER_ID
    FROM
        DATA1
    WHERE
        REVIEW_CNT = (
            SELECT MAX(REVIEW_CNT)
            FROM DATA1
        )
)

SELECT
    MR.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM
    REST_REVIEW RR INNER JOIN MEMBER_PROFILE MR
ON
    RR.MEMBER_ID = MR.MEMBER_ID
WHERE
    RR.MEMBER_ID IN (
        SELECT *
        FROM DATA2
    )
ORDER BY
    REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;
