WITH DATA AS (
    SELECT
        YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, UI.GENDER, UI.USER_ID
    FROM
        ONLINE_SALE OS INNER JOIN USER_INFO UI
    ON
        OS.USER_ID = UI.USER_ID
    GROUP BY
        YEAR(SALES_DATE), MONTH(SALES_DATE), UI.GENDER, UI.USER_ID
    HAVING
        UI.GENDER IS NOT NULL
    ORDER BY
        YEAR ASC, MONTH ASC, UI.GENDER ASC
)

SELECT
    YEAR, MONTH, GENDER, COUNT(*) USERS
FROM
    DATA
GROUP BY
    YEAR, MONTH, GENDER
