WITH DATA1 AS (
    SELECT
        CATEGORY, MAX(PRICE) MAX_PRICE
    FROM
        FOOD_PRODUCT
    GROUP BY
        CATEGORY
)

SELECT
    FR.CATEGORY, DATA1.MAX_PRICE, FR.PRODUCT_NAME
FROM
    FOOD_PRODUCT FR INNER JOIN DATA1
ON
    FR.CATEGORY = DATA1.CATEGORY
WHERE
    FR.PRICE = MAX_PRICE
    AND (
        FR.CATEGORY LIKE '과자'
        OR FR.CATEGORY LIKE '국'
        OR FR.CATEGORY LIKE '김치'
        OR FR.CATEGORY LIKE '식용유'
    )
ORDER BY
    DATA1.MAX_PRICE DESC;
