WITH FE AS (
    SELECT SUM(CODE) SUM_CODE
    FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY = 'Front End'
), ANSWER AS (
    SELECT (
        CASE
            WHEN D.SKILL_CODE & F.SUM_CODE
                AND D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'Python')
                THEN 'A'
            WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'C#')
                THEN 'B'
            WHEN D.SKILL_CODE & F.SUM_CODE
                THEN 'C'
            ELSE NULL
        END
    ) GRADE, D.ID, D.EMAIL
    FROM DEVELOPERS D, FE F
    ORDER BY GRADE, D.ID
)

SELECT * FROM ANSWER WHERE GRADE IS NOT NULL
