WITH ALL_INFO AS (
    SELECT B.*, AVG(C.SCORE) YEAR_SCORE
    FROM HR_DEPARTMENT A INNER JOIN HR_EMPLOYEES B INNER JOIN HR_GRADE C
    ON A.DEPT_ID = B.DEPT_ID AND B.EMP_NO = C.EMP_NO
    GROUP BY B.EMP_NO
), INCEN AS (
    SELECT *, (
        CASE
            WHEN YEAR_SCORE >= 96 THEN 'S'
            WHEN YEAR_SCORE >= 90 THEN 'A'
            WHEN YEAR_SCORE >= 80 THEN 'B'
            ELSE 'C'
        END
    ) GRADE
    FROM ALL_INFO
)

SELECT EMP_NO, EMP_NAME, GRADE, (
    CASE
        WHEN GRADE LIKE 'S' THEN SAL * 0.2
        WHEN GRADE LIKE 'A' THEN SAL * 0.15
        WHEN GRADE LIKE 'B' THEN SAL * 0.1
        ELSE 0
    END
) BONUS
FROM INCEN
ORDER BY EMP_NO
