WITH ONL AS (
    SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM
        ONLINE_SALE
    WHERE
        SALES_DATE LIKE '2022-03%'
), OFF AS (
    SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
    FROM
        OFFLINE_SALE
    WHERE
        SALES_DATE LIKE '2022-03%'
), TOTAL AS (
    SELECT
        *
    FROM
        ONL
    UNION
    SELECT
        *
    FROM
        OFF
)

SELECT
    *
FROM
    TOTAL
ORDER BY
    SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
