SELECT B.HOUR, NVL(COUNT, 0)
FROM (SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) AS COUNT
        FROM ANIMAL_OUTS
        GROUP BY TO_CHAR(DATETIME, 'HH24') 
        ORDER BY HOUR) A RIGHT JOIN
        (SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL<=24) B     
ON A.HOUR=B.HOUR
ORDER BY B.HOUR;
