WITH AP AS (
    SELECT
        A.*, P.PT_NAME
    FROM
        APPOINTMENT A LEFT JOIN PATIENT P
    ON
        A.PT_NO = P.PT_NO
    WHERE
        A.MCDP_CD LIKE 'CS'
        AND A.APNT_YMD LIKE '2022-04-13%'
        AND A.APNT_CNCL_YN LIKE 'N'
)

SELECT
    AP.APNT_NO, AP.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM
    AP LEFT JOIN DOCTOR D
ON
    AP.MDDR_ID = D.DR_ID
ORDER BY
    AP.APNT_YMD ASC;
