SELECT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) * 0.01), 0) FEE
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT C.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    ON C.CAR_ID = R.CAR_ID
    WHERE (C.CAR_TYPE LIKE '세단' OR C.CAR_TYPE LIKE 'SUV')
        AND (R.START_DATE <= '2022-11-30' AND R.END_DATE >= '2022-11-01')
    GROUP BY CAR_ID
) AND D.DURATION_TYPE LIKE '30일 이상' AND ((C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) * 0.01) BETWEEN 500000 AND 2000000)
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
