SELECT
    C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) * 0.01), 0) FEE
FROM
    CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON
    C.CAR_TYPE = D.CAR_TYPE
WHERE
    C.CAR_ID NOT IN (
        SELECT C1.CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR C1 INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R1
        ON C1.CAR_ID = R1.CAR_ID
        WHERE (C1.CAR_TYPE LIKE '세단' OR C1.CAR_TYPE LIKE 'SUV')
            AND (R1.START_DATE <= TO_DATE('2022-11-30', 'YYYY-mm-dd') AND R1.END_DATE >= TO_DATE('2022-11-01', 'YYYY-mm-dd'))
        GROUP BY C1.CAR_ID
    ) AND
    D.DURATION_TYPE LIKE '30일 이상' AND
    ((C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) * 0.01) BETWEEN 500000 AND 2000000)
ORDER BY
    FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
