WITH DATA1 AS (
    SELECT
        PRODUCT_ID, SUM(AMOUNT) TOTAL_AMOUNT
    FROM
        FOOD_ORDER
    WHERE
        PRODUCE_DATE LIKE '2022-05%'
    GROUP BY
        PRODUCT_ID
)

SELECT
    FP.PRODUCT_ID, FP.PRODUCT_NAME, PRICE * TOTAL_AMOUNT TOTAL_SALES
FROM
    FOOD_PRODUCT FP INNER JOIN DATA1
ON
    FP.PRODUCT_ID = DATA1.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, FP.PRODUCT_ID ASC
